% -------------------------------------------------------------------
%  Generated by MATLAB on 11-Dec-2023 16:07:11
%  MATLAB version: 9.14.0.2206163 (R2023a)
% -------------------------------------------------------------------
                                    

k = mpt.Parameter;
k.Value = 5;
k.Complexity = 'real';
k.CoderInfo.StorageClass = 'Custom';
k.CoderInfo.Identifier = '';
k.CoderInfo.Alignment = -1;
k.CoderInfo.CustomStorageClass = 'Global';
k.CoderInfo.CustomAttributes.MemorySection = 'Default';
k.CoderInfo.CustomAttributes.HeaderFile = '';
k.CoderInfo.CustomAttributes.DefinitionFile = '';
k.CoderInfo.CustomAttributes.Owner = '';
k.CoderInfo.CustomAttributes.PersistenceLevel = 1;
k.Description = '';
k.DataType = 'auto';
k.Min = [];
k.Max = [];
k.DocUnits = '';

x = mpt.Signal;
x.CoderInfo.StorageClass = 'Custom';
x.CoderInfo.Identifier = '';
x.CoderInfo.Alignment = -1;
x.CoderInfo.CustomStorageClass = 'Global';
x.CoderInfo.CustomAttributes.MemorySection = 'Default';
x.CoderInfo.CustomAttributes.HeaderFile = '';
x.CoderInfo.CustomAttributes.DefinitionFile = '';
x.CoderInfo.CustomAttributes.Owner = '';
x.CoderInfo.CustomAttributes.PersistenceLevel = 1;
x.Description = '';
x.DataType = 'auto';
x.Min = [];
x.Max = [];
x.DocUnits = '';
x.Dimensions = -1;
x.DimensionsMode = 'auto';
x.Complexity = 'auto';
x.SampleTime = -1;
x.InitialValue = '';

y = mpt.Signal;
y.CoderInfo.StorageClass = 'Custom';
y.CoderInfo.Identifier = '';
y.CoderInfo.Alignment = -1;
y.CoderInfo.CustomStorageClass = 'Global';
y.CoderInfo.CustomAttributes.MemorySection = 'Default';
y.CoderInfo.CustomAttributes.HeaderFile = '';
y.CoderInfo.CustomAttributes.DefinitionFile = '';
y.CoderInfo.CustomAttributes.Owner = '';
y.CoderInfo.CustomAttributes.PersistenceLevel = 1;
y.Description = '';
y.DataType = 'auto';
y.Min = [];
y.Max = [];
y.DocUnits = '';
y.Dimensions = -1;
y.DimensionsMode = 'auto';
y.Complexity = 'auto';
y.SampleTime = -1;
y.InitialValue = '';

z = mpt.Signal;
z.CoderInfo.StorageClass = 'Custom';
z.CoderInfo.Identifier = '';
z.CoderInfo.Alignment = -1;
z.CoderInfo.CustomStorageClass = 'Global';
z.CoderInfo.CustomAttributes.MemorySection = 'Default';
z.CoderInfo.CustomAttributes.HeaderFile = '';
z.CoderInfo.CustomAttributes.DefinitionFile = '';
z.CoderInfo.CustomAttributes.Owner = '';
z.CoderInfo.CustomAttributes.PersistenceLevel = 1;
z.Description = '';
z.DataType = 'auto';
z.Min = [];
z.Max = [];
z.DocUnits = '';
z.Dimensions = -1;
z.DimensionsMode = 'auto';
z.Complexity = 'auto';
z.SampleTime = -1;
z.InitialValue = '';

